#define _CFFI_

/* We try to define Py_LIMITED_API before including Python.h.

   Mess: we can only define it if Py_DEBUG, Py_TRACE_REFS and
   Py_REF_DEBUG are not defined.  This is a best-effort approximation:
   we can learn about Py_DEBUG from pyconfig.h, but it is unclear if
   the same works for the other two macros.  Py_DEBUG implies them,
   but not the other way around.

   The implementation is messy (issue #350): on Windows, with _MSC_VER,
   we have to define Py_LIMITED_API even before including pyconfig.h.
   In that case, we guess what pyconfig.h will do to the macros above,
   and check our guess after the #include.

   Note that on Windows, with CPython 3.x, you need >= 3.5 and virtualenv
   version >= 16.0.0.  With older versions of either, you don't get a
   copy of PYTHON3.DLL in the virtualenv.  We can't check the version of
   CPython *before* we even include pyconfig.h.  ffi.set_source() puts
   a ``#define _CFFI_NO_LIMITED_API'' at the start of this file if it is
   running on Windows < 3.5, as an attempt at fixing it, but that's
   arguably wrong because it may not be the target version of Python.
   Still better than nothing I guess.  As another workaround, you can
   remove the definition of Py_LIMITED_API here.

   See also 'py_limited_api' in cffi/setuptools_ext.py.
*/
#if !defined(_CFFI_USE_EMBEDDING) && !defined(Py_LIMITED_API)
#  ifdef _MSC_VER
#    if !defined(_DEBUG) && !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#    include <pyconfig.h>
     /* sanity-check: Py_LIMITED_API will cause crashes if any of these
        are also defined.  Normally, the Python file PC/pyconfig.h does not
        cause any of these to be defined, with the exception that _DEBUG
        causes Py_DEBUG.  Double-check that. */
#    ifdef Py_LIMITED_API
#      if defined(Py_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_DEBUG, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_TRACE_REFS)
#        error "pyconfig.h unexpectedly defines Py_TRACE_REFS, but Py_LIMITED_API is set"
#      endif
#      if defined(Py_REF_DEBUG)
#        error "pyconfig.h unexpectedly defines Py_REF_DEBUG, but Py_LIMITED_API is set"
#      endif
#    endif
#  else
#    include <pyconfig.h>
#    if !defined(Py_DEBUG) && !defined(Py_TRACE_REFS) && !defined(Py_REF_DEBUG) && !defined(_CFFI_NO_LIMITED_API)
#      define Py_LIMITED_API
#    endif
#  endif
#endif

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
#include <stddef.h>

/* This part is from file 'cffi/parse_c_type.h'.  It is copied at the
   beginning of C sources generated by CFFI's ffi.set_source(). */

typedef void *_cffi_opcode_t;

#define _CFFI_OP(opcode, arg)   (_cffi_opcode_t)(opcode | (((uintptr_t)(arg)) << 8))
#define _CFFI_GETOP(cffi_opcode)    ((unsigned char)(uintptr_t)cffi_opcode)
#define _CFFI_GETARG(cffi_opcode)   (((intptr_t)cffi_opcode) >> 8)

#define _CFFI_OP_PRIMITIVE       1
#define _CFFI_OP_POINTER         3
#define _CFFI_OP_ARRAY           5
#define _CFFI_OP_OPEN_ARRAY      7
#define _CFFI_OP_STRUCT_UNION    9
#define _CFFI_OP_ENUM           11
#define _CFFI_OP_FUNCTION       13
#define _CFFI_OP_FUNCTION_END   15
#define _CFFI_OP_NOOP           17
#define _CFFI_OP_BITFIELD       19
#define _CFFI_OP_TYPENAME       21
#define _CFFI_OP_CPYTHON_BLTN_V 23   // varargs
#define _CFFI_OP_CPYTHON_BLTN_N 25   // noargs
#define _CFFI_OP_CPYTHON_BLTN_O 27   // O  (i.e. a single arg)
#define _CFFI_OP_CONSTANT       29
#define _CFFI_OP_CONSTANT_INT   31
#define _CFFI_OP_GLOBAL_VAR     33
#define _CFFI_OP_DLOPEN_FUNC    35
#define _CFFI_OP_DLOPEN_CONST   37
#define _CFFI_OP_GLOBAL_VAR_F   39
#define _CFFI_OP_EXTERN_PYTHON  41

#define _CFFI_PRIM_VOID          0
#define _CFFI_PRIM_BOOL          1
#define _CFFI_PRIM_CHAR          2
#define _CFFI_PRIM_SCHAR         3
#define _CFFI_PRIM_UCHAR         4
#define _CFFI_PRIM_SHORT         5
#define _CFFI_PRIM_USHORT        6
#define _CFFI_PRIM_INT           7
#define _CFFI_PRIM_UINT          8
#define _CFFI_PRIM_LONG          9
#define _CFFI_PRIM_ULONG        10
#define _CFFI_PRIM_LONGLONG     11
#define _CFFI_PRIM_ULONGLONG    12
#define _CFFI_PRIM_FLOAT        13
#define _CFFI_PRIM_DOUBLE       14
#define _CFFI_PRIM_LONGDOUBLE   15

#define _CFFI_PRIM_WCHAR        16
#define _CFFI_PRIM_INT8         17
#define _CFFI_PRIM_UINT8        18
#define _CFFI_PRIM_INT16        19
#define _CFFI_PRIM_UINT16       20
#define _CFFI_PRIM_INT32        21
#define _CFFI_PRIM_UINT32       22
#define _CFFI_PRIM_INT64        23
#define _CFFI_PRIM_UINT64       24
#define _CFFI_PRIM_INTPTR       25
#define _CFFI_PRIM_UINTPTR      26
#define _CFFI_PRIM_PTRDIFF      27
#define _CFFI_PRIM_SIZE         28
#define _CFFI_PRIM_SSIZE        29
#define _CFFI_PRIM_INT_LEAST8   30
#define _CFFI_PRIM_UINT_LEAST8  31
#define _CFFI_PRIM_INT_LEAST16  32
#define _CFFI_PRIM_UINT_LEAST16 33
#define _CFFI_PRIM_INT_LEAST32  34
#define _CFFI_PRIM_UINT_LEAST32 35
#define _CFFI_PRIM_INT_LEAST64  36
#define _CFFI_PRIM_UINT_LEAST64 37
#define _CFFI_PRIM_INT_FAST8    38
#define _CFFI_PRIM_UINT_FAST8   39
#define _CFFI_PRIM_INT_FAST16   40
#define _CFFI_PRIM_UINT_FAST16  41
#define _CFFI_PRIM_INT_FAST32   42
#define _CFFI_PRIM_UINT_FAST32  43
#define _CFFI_PRIM_INT_FAST64   44
#define _CFFI_PRIM_UINT_FAST64  45
#define _CFFI_PRIM_INTMAX       46
#define _CFFI_PRIM_UINTMAX      47
#define _CFFI_PRIM_FLOATCOMPLEX 48
#define _CFFI_PRIM_DOUBLECOMPLEX 49
#define _CFFI_PRIM_CHAR16       50
#define _CFFI_PRIM_CHAR32       51

#define _CFFI__NUM_PRIM         52
#define _CFFI__UNKNOWN_PRIM           (-1)
#define _CFFI__UNKNOWN_FLOAT_PRIM     (-2)
#define _CFFI__UNKNOWN_LONG_DOUBLE    (-3)

#define _CFFI__IO_FILE_STRUCT         (-1)


struct _cffi_global_s {
    const char *name;
    void *address;
    _cffi_opcode_t type_op;
    void *size_or_direct_fn;  // OP_GLOBAL_VAR: size, or 0 if unknown
                              // OP_CPYTHON_BLTN_*: addr of direct function
};

struct _cffi_getconst_s {
    unsigned long long value;
    const struct _cffi_type_context_s *ctx;
    int gindex;
};

struct _cffi_struct_union_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_STRUCT_UNION
    int flags;               // _CFFI_F_* flags below
    size_t size;
    int alignment;
    int first_field_index;   // -> _cffi_fields array
    int num_fields;
};
#define _CFFI_F_UNION         0x01   // is a union, not a struct
#define _CFFI_F_CHECK_FIELDS  0x02   // complain if fields are not in the
                                     // "standard layout" or if some are missing
#define _CFFI_F_PACKED        0x04   // for CHECK_FIELDS, assume a packed struct
#define _CFFI_F_EXTERNAL      0x08   // in some other ffi.include()
#define _CFFI_F_OPAQUE        0x10   // opaque

struct _cffi_field_s {
    const char *name;
    size_t field_offset;
    size_t field_size;
    _cffi_opcode_t field_type_op;
};

struct _cffi_enum_s {
    const char *name;
    int type_index;          // -> _cffi_types, on a OP_ENUM
    int type_prim;           // _CFFI_PRIM_xxx
    const char *enumerators; // comma-delimited string
};

struct _cffi_typename_s {
    const char *name;
    int type_index;   /* if opaque, points to a possibly artificial
                         OP_STRUCT which is itself opaque */
};

struct _cffi_type_context_s {
    _cffi_opcode_t *types;
    const struct _cffi_global_s *globals;
    const struct _cffi_field_s *fields;
    const struct _cffi_struct_union_s *struct_unions;
    const struct _cffi_enum_s *enums;
    const struct _cffi_typename_s *typenames;
    int num_globals;
    int num_struct_unions;
    int num_enums;
    int num_typenames;
    const char *const *includes;
    int num_types;
    int flags;      /* future extension */
};

struct _cffi_parse_info_s {
    const struct _cffi_type_context_s *ctx;
    _cffi_opcode_t *output;
    unsigned int output_size;
    size_t error_location;
    const char *error_message;
};

struct _cffi_externpy_s {
    const char *name;
    size_t size_of_result;
    void *reserved1, *reserved2;
};

#ifdef _CFFI_INTERNAL
static int parse_c_type(struct _cffi_parse_info_s *info, const char *input);
static int search_in_globals(const struct _cffi_type_context_s *ctx,
                             const char *search, size_t search_len);
static int search_in_struct_unions(const struct _cffi_type_context_s *ctx,
                                   const char *search, size_t search_len);
#endif

/* this block of #ifs should be kept exactly identical between
   c/_cffi_backend.c, cffi/vengine_cpy.py, cffi/vengine_gen.py
   and cffi/_cffi_include.h */
#if defined(_MSC_VER)
# include <malloc.h>   /* for alloca() */
# if _MSC_VER < 1600   /* MSVC < 2010 */
   typedef __int8 int8_t;
   typedef __int16 int16_t;
   typedef __int32 int32_t;
   typedef __int64 int64_t;
   typedef unsigned __int8 uint8_t;
   typedef unsigned __int16 uint16_t;
   typedef unsigned __int32 uint32_t;
   typedef unsigned __int64 uint64_t;
   typedef __int8 int_least8_t;
   typedef __int16 int_least16_t;
   typedef __int32 int_least32_t;
   typedef __int64 int_least64_t;
   typedef unsigned __int8 uint_least8_t;
   typedef unsigned __int16 uint_least16_t;
   typedef unsigned __int32 uint_least32_t;
   typedef unsigned __int64 uint_least64_t;
   typedef __int8 int_fast8_t;
   typedef __int16 int_fast16_t;
   typedef __int32 int_fast32_t;
   typedef __int64 int_fast64_t;
   typedef unsigned __int8 uint_fast8_t;
   typedef unsigned __int16 uint_fast16_t;
   typedef unsigned __int32 uint_fast32_t;
   typedef unsigned __int64 uint_fast64_t;
   typedef __int64 intmax_t;
   typedef unsigned __int64 uintmax_t;
# else
#  include <stdint.h>
# endif
# if _MSC_VER < 1800   /* MSVC < 2013 */
#  ifndef __cplusplus
    typedef unsigned char _Bool;
#  endif
# endif
# define _cffi_float_complex_t   _Fcomplex    /* include <complex.h> for it */
# define _cffi_double_complex_t  _Dcomplex    /* include <complex.h> for it */
#else
# include <stdint.h>
# if (defined (__SVR4) && defined (__sun)) || defined(_AIX) || defined(__hpux)
#  include <alloca.h>
# endif
# define _cffi_float_complex_t   float _Complex
# define _cffi_double_complex_t  double _Complex
#endif

#ifdef __GNUC__
# define _CFFI_UNUSED_FN  __attribute__((unused))
#else
# define _CFFI_UNUSED_FN  /* nothing */
#endif

#ifdef __cplusplus
# ifndef _Bool
   typedef bool _Bool;   /* semi-hackish: C++ has no _Bool; bool is builtin */
# endif
#endif

/**********  CPython-specific section  **********/
#ifndef PYPY_VERSION


#if PY_MAJOR_VERSION >= 3
# define PyInt_FromLong PyLong_FromLong
#endif

#define _cffi_from_c_double PyFloat_FromDouble
#define _cffi_from_c_float PyFloat_FromDouble
#define _cffi_from_c_long PyInt_FromLong
#define _cffi_from_c_ulong PyLong_FromUnsignedLong
#define _cffi_from_c_longlong PyLong_FromLongLong
#define _cffi_from_c_ulonglong PyLong_FromUnsignedLongLong
#define _cffi_from_c__Bool PyBool_FromLong

#define _cffi_to_c_double PyFloat_AsDouble
#define _cffi_to_c_float PyFloat_AsDouble

#define _cffi_from_c_int(x, type)                                        \
    (((type)-1) > 0 ? /* unsigned */                                     \
        (sizeof(type) < sizeof(long) ?                                   \
            PyInt_FromLong((long)x) :                                    \
         sizeof(type) == sizeof(long) ?                                  \
            PyLong_FromUnsignedLong((unsigned long)x) :                  \
            PyLong_FromUnsignedLongLong((unsigned long long)x)) :        \
        (sizeof(type) <= sizeof(long) ?                                  \
            PyInt_FromLong((long)x) :                                    \
            PyLong_FromLongLong((long long)x)))

#define _cffi_to_c_int(o, type)                                          \
    ((type)(                                                             \
     sizeof(type) == 1 ? (((type)-1) > 0 ? (type)_cffi_to_c_u8(o)        \
                                         : (type)_cffi_to_c_i8(o)) :     \
     sizeof(type) == 2 ? (((type)-1) > 0 ? (type)_cffi_to_c_u16(o)       \
                                         : (type)_cffi_to_c_i16(o)) :    \
     sizeof(type) == 4 ? (((type)-1) > 0 ? (type)_cffi_to_c_u32(o)       \
                                         : (type)_cffi_to_c_i32(o)) :    \
     sizeof(type) == 8 ? (((type)-1) > 0 ? (type)_cffi_to_c_u64(o)       \
                                         : (type)_cffi_to_c_i64(o)) :    \
     (Py_FatalError("unsupported size for type " #type), (type)0)))

#define _cffi_to_c_i8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[1])
#define _cffi_to_c_u8                                                    \
                 ((int(*)(PyObject *))_cffi_exports[2])
#define _cffi_to_c_i16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[3])
#define _cffi_to_c_u16                                                   \
                 ((int(*)(PyObject *))_cffi_exports[4])
#define _cffi_to_c_i32                                                   \
                 ((int(*)(PyObject *))_cffi_exports[5])
#define _cffi_to_c_u32                                                   \
                 ((unsigned int(*)(PyObject *))_cffi_exports[6])
#define _cffi_to_c_i64                                                   \
                 ((long long(*)(PyObject *))_cffi_exports[7])
#define _cffi_to_c_u64                                                   \
                 ((unsigned long long(*)(PyObject *))_cffi_exports[8])
#define _cffi_to_c_char                                                  \
                 ((int(*)(PyObject *))_cffi_exports[9])
#define _cffi_from_c_pointer                                             \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[10])
#define _cffi_to_c_pointer                                               \
    ((char *(*)(PyObject *, struct _cffi_ctypedescr *))_cffi_exports[11])
#define _cffi_get_struct_layout                                          \
    not used any more
#define _cffi_restore_errno                                              \
    ((void(*)(void))_cffi_exports[13])
#define _cffi_save_errno                                                 \
    ((void(*)(void))_cffi_exports[14])
#define _cffi_from_c_char                                                \
    ((PyObject *(*)(char))_cffi_exports[15])
#define _cffi_from_c_deref                                               \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[16])
#define _cffi_to_c                                                       \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[17])
#define _cffi_from_c_struct                                              \
    ((PyObject *(*)(char *, struct _cffi_ctypedescr *))_cffi_exports[18])
#define _cffi_to_c_wchar_t                                               \
    ((_cffi_wchar_t(*)(PyObject *))_cffi_exports[19])
#define _cffi_from_c_wchar_t                                             \
    ((PyObject *(*)(_cffi_wchar_t))_cffi_exports[20])
#define _cffi_to_c_long_double                                           \
    ((long double(*)(PyObject *))_cffi_exports[21])
#define _cffi_to_c__Bool                                                 \
    ((_Bool(*)(PyObject *))_cffi_exports[22])
#define _cffi_prepare_pointer_call_argument                              \
    ((Py_ssize_t(*)(struct _cffi_ctypedescr *,                           \
                    PyObject *, char **))_cffi_exports[23])
#define _cffi_convert_array_from_object                                  \
    ((int(*)(char *, struct _cffi_ctypedescr *, PyObject *))_cffi_exports[24])
#define _CFFI_CPIDX  25
#define _cffi_call_python                                                \
    ((void(*)(struct _cffi_externpy_s *, char *))_cffi_exports[_CFFI_CPIDX])
#define _cffi_to_c_wchar3216_t                                           \
    ((int(*)(PyObject *))_cffi_exports[26])
#define _cffi_from_c_wchar3216_t                                         \
    ((PyObject *(*)(int))_cffi_exports[27])
#define _CFFI_NUM_EXPORTS 28

struct _cffi_ctypedescr;

static void *_cffi_exports[_CFFI_NUM_EXPORTS];

#define _cffi_type(index)   (                           \
    assert((((uintptr_t)_cffi_types[index]) & 1) == 0), \
    (struct _cffi_ctypedescr *)_cffi_types[index])

static PyObject *_cffi_init(const char *module_name, Py_ssize_t version,
                            const struct _cffi_type_context_s *ctx)
{
    PyObject *module, *o_arg, *new_module;
    void *raw[] = {
        (void *)module_name,
        (void *)version,
        (void *)_cffi_exports,
        (void *)ctx,
    };

    module = PyImport_ImportModule("_cffi_backend");
    if (module == NULL)
        goto failure;

    o_arg = PyLong_FromVoidPtr((void *)raw);
    if (o_arg == NULL)
        goto failure;

    new_module = PyObject_CallMethod(
        module, (char *)"_init_cffi_1_0_external_module", (char *)"O", o_arg);

    Py_DECREF(o_arg);
    Py_DECREF(module);
    return new_module;

  failure:
    Py_XDECREF(module);
    return NULL;
}


#ifdef HAVE_WCHAR_H
typedef wchar_t _cffi_wchar_t;
#else
typedef uint16_t _cffi_wchar_t;   /* same random pick as _cffi_backend.c */
#endif

_CFFI_UNUSED_FN static uint16_t _cffi_to_c_char16_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return (uint16_t)_cffi_to_c_wchar_t(o);
    else
        return (uint16_t)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char16_t(uint16_t x)
{
    if (sizeof(_cffi_wchar_t) == 2)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

_CFFI_UNUSED_FN static int _cffi_to_c_char32_t(PyObject *o)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return (int)_cffi_to_c_wchar_t(o);
    else
        return (int)_cffi_to_c_wchar3216_t(o);
}

_CFFI_UNUSED_FN static PyObject *_cffi_from_c_char32_t(unsigned int x)
{
    if (sizeof(_cffi_wchar_t) == 4)
        return _cffi_from_c_wchar_t((_cffi_wchar_t)x);
    else
        return _cffi_from_c_wchar3216_t((int)x);
}

union _cffi_union_alignment_u {
    unsigned char m_char;
    unsigned short m_short;
    unsigned int m_int;
    unsigned long m_long;
    unsigned long long m_longlong;
    float m_float;
    double m_double;
    long double m_longdouble;
};

struct _cffi_freeme_s {
    struct _cffi_freeme_s *next;
    union _cffi_union_alignment_u alignment;
};

_CFFI_UNUSED_FN static int
_cffi_convert_array_argument(struct _cffi_ctypedescr *ctptr, PyObject *arg,
                             char **output_data, Py_ssize_t datasize,
                             struct _cffi_freeme_s **freeme)
{
    char *p;
    if (datasize < 0)
        return -1;

    p = *output_data;
    if (p == NULL) {
        struct _cffi_freeme_s *fp = (struct _cffi_freeme_s *)PyObject_Malloc(
            offsetof(struct _cffi_freeme_s, alignment) + (size_t)datasize);
        if (fp == NULL)
            return -1;
        fp->next = *freeme;
        *freeme = fp;
        p = *output_data = (char *)&fp->alignment;
    }
    memset((void *)p, 0, (size_t)datasize);
    return _cffi_convert_array_from_object(p, ctptr, arg);
}

_CFFI_UNUSED_FN static void
_cffi_free_array_arguments(struct _cffi_freeme_s *freeme)
{
    do {
        void *p = (void *)freeme;
        freeme = freeme->next;
        PyObject_Free(p);
    } while (freeme != NULL);
}

/**********  end CPython-specific section  **********/
#else
_CFFI_UNUSED_FN
static void (*_cffi_call_python_org)(struct _cffi_externpy_s *, char *);
# define _cffi_call_python  _cffi_call_python_org
#endif


#define _cffi_array_len(array)   (sizeof(array) / sizeof((array)[0]))

#define _cffi_prim_int(size, sign)                                      \
    ((size) == 1 ? ((sign) ? _CFFI_PRIM_INT8  : _CFFI_PRIM_UINT8)  :    \
     (size) == 2 ? ((sign) ? _CFFI_PRIM_INT16 : _CFFI_PRIM_UINT16) :    \
     (size) == 4 ? ((sign) ? _CFFI_PRIM_INT32 : _CFFI_PRIM_UINT32) :    \
     (size) == 8 ? ((sign) ? _CFFI_PRIM_INT64 : _CFFI_PRIM_UINT64) :    \
     _CFFI__UNKNOWN_PRIM)

#define _cffi_prim_float(size)                                          \
    ((size) == sizeof(float) ? _CFFI_PRIM_FLOAT :                       \
     (size) == sizeof(double) ? _CFFI_PRIM_DOUBLE :                     \
     (size) == sizeof(long double) ? _CFFI__UNKNOWN_LONG_DOUBLE :       \
     _CFFI__UNKNOWN_FLOAT_PRIM)

#define _cffi_check_int(got, got_nonpos, expected)      \
    ((got_nonpos) == (expected <= 0) &&                 \
     (got) == (unsigned long long)expected)

#ifdef MS_WIN32
# define _cffi_stdcall  __stdcall
#else
# define _cffi_stdcall  /* nothing */
#endif

#ifdef __cplusplus
}
#endif

/************************************************************/


// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCx version 0.10.0.
//
// This code was generated with the following options:
//
//  {'epsilon': 1e-14,
//   'part': 'full',
//   'scalar_type': <class 'numpy.float64'>,
//   'sum_factorization': False,
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'verbosity': 30}

#include <math.h>
#include <stdalign.h>
#include <stdlib.h>
#include <string.h>
#include <ufcx.h>



// Code for integral integral_45b3f1e87369b432409937821602708537a52694_quadrilateral

void tabulate_tensor_integral_45b3f1e87369b432409937821602708537a52694_quadrilateral(double* restrict A,
                                    const double* restrict w,
                                    const double* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    void* custom_data)
{
// Quadrature rules
static const double weights_504[36] = {0.007338020422245101, 0.01545182334309584, 0.02004127932945165, 0.02004127932945165, 0.01545182334309583, 0.007338020422245093, 0.01545182334309584, 0.03253722814704188, 0.04220134177189697, 0.04220134177189697, 0.03253722814704186, 0.01545182334309582, 0.02004127932945165, 0.04220134177189697, 0.05473586254182414, 0.05473586254182414, 0.04220134177189694, 0.02004127932945163, 0.02004127932945165, 0.04220134177189697, 0.05473586254182414, 0.05473586254182414, 0.04220134177189694, 0.02004127932945163, 0.01545182334309583, 0.03253722814704186, 0.04220134177189694, 0.04220134177189694, 0.03253722814704185, 0.01545182334309581, 0.007338020422245093, 0.01545182334309582, 0.02004127932945163, 0.02004127932945163, 0.01545182334309581, 0.007338020422245086};
// Precomputed values of basis functions and precomputations
// FE* dimensions: [permutation][entities][points][dofs]
static const double FE0_C0_Q504[1][1][36][4] = {{{{0.9336096058311414, 0.03262515127043441, 0.03262515127043441, 0.001140091627989582},
  {0.8025591240135445, 0.02804556921958768, 0.1636756330880314, 0.005719673678836316},
  {0.5983984542032248, 0.02091113883837369, 0.3678363028983512, 0.01285410406005031},
  {0.3678363028983512, 0.01285410406005029, 0.5983984542032248, 0.02091113883837366},
  {0.1636756330880314, 0.005719673678836293, 0.8025591240135446, 0.02804556921958763},
  {0.03262515127043458, 0.001140091627989538, 0.9336096058311416, 0.0326251512704344},
  {0.8025591240135443, 0.1636756330880314, 0.02804556921958765, 0.005719673678836344},
  {0.6899041564209056, 0.1407005368122266, 0.1407005368122265, 0.02869476995464123},
  {0.5144014545446529, 0.1049081384969456, 0.3162032386884794, 0.06448716826992215},
  {0.3162032386884794, 0.06448716826992214, 0.5144014545446529, 0.1049081384969456},
  {0.1407005368122265, 0.02869476995464122, 0.6899041564209057, 0.1407005368122265},
  {0.02804556921958775, 0.005719673678836358, 0.8025591240135446, 0.1636756330880314},
  {0.5983984542032247, 0.3678363028983512, 0.02091113883837367, 0.0128541040600503},
  {0.5144014545446529, 0.3162032386884794, 0.1049081384969456, 0.06448716826992215},
  {0.3835443720333503, 0.2357652210082481, 0.2357652210082481, 0.1449251859501534},
  {0.2357652210082481, 0.1449251859501534, 0.3835443720333503, 0.2357652210082481},
  {0.1049081384969456, 0.06448716826992212, 0.5144014545446529, 0.3162032386884794},
  {0.02091113883837374, 0.01285410406005033, 0.5983984542032248, 0.3678363028983512},
  {0.3678363028983512, 0.5983984542032248, 0.0128541040600503, 0.02091113883837366},
  {0.3162032386884794, 0.5144014545446529, 0.06448716826992214, 0.1049081384969456},
  {0.2357652210082481, 0.3835443720333503, 0.1449251859501534, 0.2357652210082481},
  {0.1449251859501534, 0.2357652210082481, 0.2357652210082481, 0.3835443720333503},
  {0.06448716826992211, 0.1049081384969456, 0.3162032386884794, 0.5144014545446529},
  {0.01285410406005031, 0.02091113883837373, 0.3678363028983512, 0.5983984542032248},
  {0.1636756330880314, 0.8025591240135446, 0.005719673678836293, 0.02804556921958766},
  {0.1407005368122265, 0.6899041564209059, 0.02869476995464122, 0.1407005368122265},
  {0.1049081384969456, 0.5144014545446529, 0.06448716826992212, 0.3162032386884794},
  {0.0644871682699221, 0.3162032386884794, 0.1049081384969455, 0.5144014545446529},
  {0.02869476995464116, 0.1407005368122265, 0.1407005368122265, 0.689904156420906},
  {0.00571967367883629, 0.02804556921958772, 0.1636756330880313, 0.8025591240135448},
  {0.03262515127043458, 0.9336096058311416, 0.001140091627989538, 0.0326251512704344},
  {0.02804556921958778, 0.8025591240135446, 0.005719673678836358, 0.1636756330880314},
  {0.02091113883837376, 0.5983984542032248, 0.01285410406005033, 0.3678363028983512},
  {0.0128541040600503, 0.3678363028983512, 0.02091113883837373, 0.5983984542032248},
  {0.00571967367883629, 0.1636756330880313, 0.02804556921958772, 0.8025591240135448},
  {0.001140091627989522, 0.03262515127043449, 0.03262515127043449, 0.9336096058311417}}}};
static const double FE1_C0_D10_Q504[1][1][36][4] = {{{{-0.9662347571015757, 0.9662347571015759, -0.03376524289842398, 0.03376524289842388},
  {-0.830604693233132, 0.8306046932331322, -0.1693953067668677, 0.1693953067668677},
  {-0.6193095930415984, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015},
  {-0.3806904069584015, 0.3806904069584015, -0.6193095930415984, 0.6193095930415985},
  {-0.1693953067668678, 0.1693953067668677, -0.8306046932331322, 0.8306046932331325},
  {-0.03376524289842422, 0.03376524289842404, -0.9662347571015759, 0.9662347571015761},
  {-0.9662347571015757, 0.9662347571015759, -0.03376524289842398, 0.03376524289842388},
  {-0.830604693233132, 0.8306046932331322, -0.1693953067668677, 0.1693953067668677},
  {-0.6193095930415984, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015},
  {-0.3806904069584015, 0.3806904069584015, -0.6193095930415984, 0.6193095930415985},
  {-0.1693953067668678, 0.1693953067668677, -0.8306046932331322, 0.8306046932331325},
  {-0.03376524289842422, 0.03376524289842404, -0.9662347571015759, 0.9662347571015761},
  {-0.9662347571015757, 0.9662347571015759, -0.03376524289842398, 0.03376524289842388},
  {-0.830604693233132, 0.8306046932331322, -0.1693953067668677, 0.1693953067668677},
  {-0.6193095930415984, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015},
  {-0.3806904069584015, 0.3806904069584015, -0.6193095930415984, 0.6193095930415985},
  {-0.1693953067668678, 0.1693953067668677, -0.8306046932331322, 0.8306046932331325},
  {-0.03376524289842422, 0.03376524289842404, -0.9662347571015759, 0.9662347571015761},
  {-0.9662347571015757, 0.9662347571015759, -0.03376524289842398, 0.03376524289842388},
  {-0.830604693233132, 0.8306046932331322, -0.1693953067668677, 0.1693953067668677},
  {-0.6193095930415984, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015},
  {-0.3806904069584015, 0.3806904069584015, -0.6193095930415984, 0.6193095930415985},
  {-0.1693953067668678, 0.1693953067668677, -0.8306046932331322, 0.8306046932331325},
  {-0.03376524289842422, 0.03376524289842404, -0.9662347571015759, 0.9662347571015761},
  {-0.9662347571015757, 0.9662347571015759, -0.03376524289842398, 0.03376524289842388},
  {-0.830604693233132, 0.8306046932331322, -0.1693953067668677, 0.1693953067668677},
  {-0.6193095930415984, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015},
  {-0.3806904069584015, 0.3806904069584015, -0.6193095930415984, 0.6193095930415985},
  {-0.1693953067668678, 0.1693953067668677, -0.8306046932331322, 0.8306046932331325},
  {-0.03376524289842422, 0.03376524289842404, -0.9662347571015759, 0.9662347571015761},
  {-0.9662347571015757, 0.9662347571015759, -0.03376524289842398, 0.03376524289842388},
  {-0.830604693233132, 0.8306046932331322, -0.1693953067668677, 0.1693953067668677},
  {-0.6193095930415984, 0.6193095930415985, -0.3806904069584015, 0.3806904069584015},
  {-0.3806904069584015, 0.3806904069584015, -0.6193095930415984, 0.6193095930415985},
  {-0.1693953067668678, 0.1693953067668677, -0.8306046932331322, 0.8306046932331325},
  {-0.03376524289842422, 0.03376524289842404, -0.9662347571015759, 0.9662347571015761}}}};
static const double FE3_C0_D01_Q504[1][1][36][4] = {{{{-0.9662347571015757, -0.03376524289842398, 0.9662347571015759, 0.03376524289842388},
  {-0.9662347571015757, -0.03376524289842398, 0.9662347571015759, 0.03376524289842388},
  {-0.9662347571015757, -0.03376524289842398, 0.9662347571015759, 0.03376524289842388},
  {-0.9662347571015757, -0.03376524289842398, 0.9662347571015759, 0.03376524289842388},
  {-0.9662347571015757, -0.03376524289842398, 0.9662347571015759, 0.03376524289842388},
  {-0.9662347571015757, -0.03376524289842398, 0.9662347571015759, 0.03376524289842388},
  {-0.830604693233132, -0.1693953067668677, 0.8306046932331322, 0.1693953067668677},
  {-0.830604693233132, -0.1693953067668677, 0.8306046932331322, 0.1693953067668677},
  {-0.830604693233132, -0.1693953067668677, 0.8306046932331322, 0.1693953067668677},
  {-0.830604693233132, -0.1693953067668677, 0.8306046932331322, 0.1693953067668677},
  {-0.830604693233132, -0.1693953067668677, 0.8306046932331322, 0.1693953067668677},
  {-0.830604693233132, -0.1693953067668677, 0.8306046932331322, 0.1693953067668677},
  {-0.6193095930415984, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015},
  {-0.6193095930415984, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015},
  {-0.6193095930415984, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015},
  {-0.6193095930415984, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015},
  {-0.6193095930415984, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015},
  {-0.6193095930415984, -0.3806904069584015, 0.6193095930415985, 0.3806904069584015},
  {-0.3806904069584015, -0.6193095930415984, 0.3806904069584015, 0.6193095930415985},
  {-0.3806904069584015, -0.6193095930415984, 0.3806904069584015, 0.6193095930415985},
  {-0.3806904069584015, -0.6193095930415984, 0.3806904069584015, 0.6193095930415985},
  {-0.3806904069584015, -0.6193095930415984, 0.3806904069584015, 0.6193095930415985},
  {-0.3806904069584015, -0.6193095930415984, 0.3806904069584015, 0.6193095930415985},
  {-0.3806904069584015, -0.6193095930415984, 0.3806904069584015, 0.6193095930415985},
  {-0.1693953067668678, -0.8306046932331322, 0.1693953067668677, 0.8306046932331325},
  {-0.1693953067668678, -0.8306046932331322, 0.1693953067668677, 0.8306046932331325},
  {-0.1693953067668678, -0.8306046932331322, 0.1693953067668677, 0.8306046932331325},
  {-0.1693953067668678, -0.8306046932331322, 0.1693953067668677, 0.8306046932331325},
  {-0.1693953067668678, -0.8306046932331322, 0.1693953067668677, 0.8306046932331325},
  {-0.1693953067668678, -0.8306046932331322, 0.1693953067668677, 0.8306046932331325},
  {-0.03376524289842422, -0.9662347571015759, 0.03376524289842404, 0.9662347571015761},
  {-0.03376524289842422, -0.9662347571015759, 0.03376524289842404, 0.9662347571015761},
  {-0.03376524289842422, -0.9662347571015759, 0.03376524289842404, 0.9662347571015761},
  {-0.03376524289842422, -0.9662347571015759, 0.03376524289842404, 0.9662347571015761},
  {-0.03376524289842422, -0.9662347571015759, 0.03376524289842404, 0.9662347571015761},
  {-0.03376524289842422, -0.9662347571015759, 0.03376524289842404, 0.9662347571015761}}}};
double sp_504_0 = 2.0 * w[1];
for (int iq = 0; iq < 36; ++iq)
{
  // ------------------------ 
  // Section: Function
  // Inputs: w, FE3_C0_D01_Q504
  // Outputs: w3_d010_c0
  double w3_d010_c0 = 0.0;
  {
    for (int ic = 0; ic < 4; ++ic)
    {
      w3_d010_c0 += w[6 + (ic) * 2] * FE3_C0_D01_Q504[0][0][iq][ic];
    }
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Jacobian
  // Inputs: coordinate_dofs, FE1_C0_D10_Q504, FE3_C0_D01_Q504
  // Outputs: J0_c1, J0_c3, J0_c4, J0_c0, J0_c5, J0_c2
  double J0_c1 = 0.0;
  double J0_c0 = 0.0;
  double J0_c2 = 0.0;
  double J0_c4 = 0.0;
  double J0_c3 = 0.0;
  double J0_c5 = 0.0;
  {
    for (int ic = 0; ic < 4; ++ic)
    {
      J0_c1 += coordinate_dofs[(ic) * 3] * FE3_C0_D01_Q504[0][0][iq][ic];
      J0_c0 += coordinate_dofs[(ic) * 3] * FE1_C0_D10_Q504[0][0][iq][ic];
      J0_c2 += coordinate_dofs[(ic) * 3 + 1] * FE1_C0_D10_Q504[0][0][iq][ic];
      J0_c4 += coordinate_dofs[(ic) * 3 + 2] * FE1_C0_D10_Q504[0][0][iq][ic];
      J0_c3 += coordinate_dofs[(ic) * 3 + 1] * FE3_C0_D01_Q504[0][0][iq][ic];
      J0_c5 += coordinate_dofs[(ic) * 3 + 2] * FE3_C0_D01_Q504[0][0][iq][ic];
    }
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Function
  // Inputs: w, FE1_C0_D10_Q504
  // Outputs: w3_d100_c0
  double w3_d100_c0 = 0.0;
  {
    for (int ic = 0; ic < 4; ++ic)
    {
      w3_d100_c0 += w[6 + (ic) * 2] * FE1_C0_D10_Q504[0][0][iq][ic];
    }
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Function
  // Inputs: w, FE3_C0_D01_Q504
  // Outputs: w3_d010_c1
  double w3_d010_c1 = 0.0;
  {
    for (int ic = 0; ic < 4; ++ic)
    {
      w3_d010_c1 += w[6 + ((ic) * 2 + 1)] * FE3_C0_D01_Q504[0][0][iq][ic];
    }
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Function
  // Inputs: w, FE1_C0_D10_Q504
  // Outputs: w3_d100_c1
  double w3_d100_c1 = 0.0;
  {
    for (int ic = 0; ic < 4; ++ic)
    {
      w3_d100_c1 += w[6 + ((ic) * 2 + 1)] * FE1_C0_D10_Q504[0][0][iq][ic];
    }
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Function
  // Inputs: w, FE0_C0_Q504
  // Outputs: w2
  double w2 = 0.0;
  {
    for (int ic = 0; ic < 4; ++ic)
    {
      w2 += w[2 + (ic)] * FE0_C0_Q504[0][0][iq][ic];
    }
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Intermediates
  // Inputs: w3_d010_c0, J0_c1, J0_c3, J0_c4, J0_c0, J0_c5, J0_c2, w3_d100_c0, w3_d010_c1, w3_d100_c1, w2
  // Outputs: fw0
  double fw0 = 0;
  {
    double sv_504_0 = J0_c0 * J0_c0;
    double sv_504_1 = J0_c2 * J0_c2;
    double sv_504_2 = sv_504_0 + sv_504_1;
    double sv_504_3 = J0_c4 * J0_c4;
    double sv_504_4 = sv_504_2 + sv_504_3;
    double sv_504_5 = J0_c1 * J0_c1;
    double sv_504_6 = J0_c3 * J0_c3;
    double sv_504_7 = sv_504_5 + sv_504_6;
    double sv_504_8 = J0_c5 * J0_c5;
    double sv_504_9 = sv_504_7 + sv_504_8;
    double sv_504_10 = sv_504_4 * sv_504_9;
    double sv_504_11 = J0_c0 * J0_c1;
    double sv_504_12 = J0_c2 * J0_c3;
    double sv_504_13 = sv_504_11 + sv_504_12;
    double sv_504_14 = J0_c4 * J0_c5;
    double sv_504_15 = sv_504_13 + sv_504_14;
    double sv_504_16 = sv_504_15 * sv_504_15;
    double sv_504_17 = -sv_504_16;
    double sv_504_18 = sv_504_10 + sv_504_17;
    double sv_504_19 = sv_504_4 / sv_504_18;
    double sv_504_20 = J0_c1 * sv_504_19;
    double sv_504_21 = -sv_504_15;
    double sv_504_22 = sv_504_21 / sv_504_18;
    double sv_504_23 = J0_c0 * sv_504_22;
    double sv_504_24 = sv_504_20 + sv_504_23;
    double sv_504_25 = w3_d010_c0 * sv_504_24;
    double sv_504_26 = sv_504_9 / sv_504_18;
    double sv_504_27 = J0_c0 * sv_504_26;
    double sv_504_28 = J0_c1 * sv_504_22;
    double sv_504_29 = sv_504_27 + sv_504_28;
    double sv_504_30 = w3_d100_c0 * sv_504_29;
    double sv_504_31 = sv_504_25 + sv_504_30;
    double sv_504_32 = sv_504_31 * sp_504_0;
    double sv_504_33 = J0_c3 * sv_504_19;
    double sv_504_34 = J0_c2 * sv_504_22;
    double sv_504_35 = sv_504_33 + sv_504_34;
    double sv_504_36 = w3_d010_c1 * sv_504_35;
    double sv_504_37 = J0_c2 * sv_504_26;
    double sv_504_38 = J0_c3 * sv_504_22;
    double sv_504_39 = sv_504_37 + sv_504_38;
    double sv_504_40 = w3_d100_c1 * sv_504_39;
    double sv_504_41 = sv_504_36 + sv_504_40;
    double sv_504_42 = sv_504_31 + sv_504_41;
    double sv_504_43 = sv_504_42 * w[0];
    double sv_504_44 = sv_504_32 + sv_504_43;
    double sv_504_45 = 0.01 * w2;
    double sv_504_46 = sp_504_0 * sv_504_45;
    double sv_504_47 = sv_504_45 + sv_504_45;
    double sv_504_48 = sv_504_47 * w[0];
    double sv_504_49 = sv_504_46 + sv_504_48;
    double sv_504_50 = -sv_504_49;
    double sv_504_51 = sv_504_44 + sv_504_50;
    double sv_504_52 = pow(sv_504_51, 2);
    double sv_504_53 = sv_504_41 * sp_504_0;
    double sv_504_54 = sv_504_53 + sv_504_43;
    double sv_504_55 = sv_504_54 + sv_504_50;
    double sv_504_56 = pow(sv_504_55, 2);
    double sv_504_57 = sv_504_52 + sv_504_56;
    double sv_504_58 = sv_504_51 * sv_504_55;
    double sv_504_59 = -sv_504_58;
    double sv_504_60 = sv_504_57 + sv_504_59;
    double sv_504_61 = w3_d010_c1 * sv_504_24;
    double sv_504_62 = w3_d100_c1 * sv_504_29;
    double sv_504_63 = sv_504_61 + sv_504_62;
    double sv_504_64 = w3_d010_c0 * sv_504_35;
    double sv_504_65 = w3_d100_c0 * sv_504_39;
    double sv_504_66 = sv_504_64 + sv_504_65;
    double sv_504_67 = sv_504_63 + sv_504_66;
    double sv_504_68 = 0.5 * sv_504_67;
    double sv_504_69 = sv_504_68 * sp_504_0;
    double sv_504_70 = pow(sv_504_69, 2);
    double sv_504_71 = 3.0 * sv_504_70;
    double sv_504_72 = sv_504_60 + sv_504_71;
    double sv_504_73 = sqrt(sv_504_72);
    double sv_504_74 = J0_c2 * J0_c5;
    double sv_504_75 = J0_c3 * J0_c4;
    double sv_504_76 = -sv_504_75;
    double sv_504_77 = sv_504_74 + sv_504_76;
    double sv_504_78 = sv_504_77 * sv_504_77;
    double sv_504_79 = J0_c1 * J0_c4;
    double sv_504_80 = J0_c0 * J0_c5;
    double sv_504_81 = -sv_504_80;
    double sv_504_82 = sv_504_79 + sv_504_81;
    double sv_504_83 = sv_504_82 * sv_504_82;
    double sv_504_84 = sv_504_78 + sv_504_83;
    double sv_504_85 = J0_c0 * J0_c3;
    double sv_504_86 = J0_c1 * J0_c2;
    double sv_504_87 = -sv_504_86;
    double sv_504_88 = sv_504_85 + sv_504_87;
    double sv_504_89 = sv_504_88 * sv_504_88;
    double sv_504_90 = sv_504_84 + sv_504_89;
    double sv_504_91 = sqrt(sv_504_90);
    double sv_504_92 = sv_504_91;
    double sv_504_93 = fabs(sv_504_92);
    double sv_504_94 = sv_504_93 * sv_504_73;
    fw0 = sv_504_94 * weights_504[iq];
  }
  // ------------------------ 
  // ------------------------ 
  // Section: Tensor Computation
  // Inputs: fw0
  // Outputs: A
  {
    for (int i = 0; i < 1; ++i)
    {
      A[(i)] += fw0 * 1;
    }
  }
  // ------------------------ 
}

}

bool enabled_coefficients_integral_45b3f1e87369b432409937821602708537a52694_quadrilateral[4] = {1, 1, 1, 1};

ufcx_integral integral_45b3f1e87369b432409937821602708537a52694_quadrilateral =
{
  .enabled_coefficients = enabled_coefficients_integral_45b3f1e87369b432409937821602708537a52694_quadrilateral,
  .tabulate_tensor_float32 = NULL,
  .tabulate_tensor_float64 = tabulate_tensor_integral_45b3f1e87369b432409937821602708537a52694_quadrilateral,
  .tabulate_tensor_complex64 = NULL,
  .tabulate_tensor_complex128 = NULL,
  .needs_facet_permutations = false,
  .coordinate_element_hash = UINT64_C(16933917319056390650),
  .domain = 4,
};

// End of code for integral integral_45b3f1e87369b432409937821602708537a52694_quadrilateral

// Code for form form_0ebe0cfd226e9065e104ecf742cb81f304263891

int original_coefficient_position_form_0ebe0cfd226e9065e104ecf742cb81f304263891[4] = {0, 1, 2, 3};
uint64_t finite_element_hashes_form_0ebe0cfd226e9065e104ecf742cb81f304263891[5] = {UINT64_C(16933917319056550412), UINT64_C(16933917319056550412), UINT64_C(16933917319056550412), UINT64_C(16933917319056390650), UINT64_C(16933917319056390650)};
int form_integral_offsets_form_0ebe0cfd226e9065e104ecf742cb81f304263891[6] = {0, 1, 1, 1, 1, 1};
static ufcx_integral* form_integrals_form_0ebe0cfd226e9065e104ecf742cb81f304263891[1] = {&integral_45b3f1e87369b432409937821602708537a52694_quadrilateral};
int form_integral_ids_form_0ebe0cfd226e9065e104ecf742cb81f304263891[1] = {-1};

static const char* coefficient_names_form_0ebe0cfd226e9065e104ecf742cb81f304263891[4] = {"w0", "w1", "w2", "w3"};




ufcx_form form_0ebe0cfd226e9065e104ecf742cb81f304263891 =
{

  .signature = "350a05353312539a5f85e93d25bf4e3df15dcf10e1c25fd7cec37bc8c3d13dd6cfa7825fd19ede94489c36a993c7cae71614dcf1c74405e858ea1551449a951c",
  .rank = 1,

  .num_coefficients = 4,
  .original_coefficient_positions = original_coefficient_position_form_0ebe0cfd226e9065e104ecf742cb81f304263891,
  .coefficient_name_map = coefficient_names_form_0ebe0cfd226e9065e104ecf742cb81f304263891,

  .num_constants = 0,
  .constant_ranks = NULL,
  .constant_shapes = NULL,
  .constant_name_map = NULL,

  .finite_element_hashes = finite_element_hashes_form_0ebe0cfd226e9065e104ecf742cb81f304263891,

  .form_integrals = form_integrals_form_0ebe0cfd226e9065e104ecf742cb81f304263891,
  .form_integral_ids = form_integral_ids_form_0ebe0cfd226e9065e104ecf742cb81f304263891,
  .form_integral_offsets = form_integral_offsets_form_0ebe0cfd226e9065e104ecf742cb81f304263891
};

// Alias name
ufcx_form* form_libffcx_forms_f9460830725f7d7c5dac003b7f248d97359f8a1f_0 = &form_0ebe0cfd226e9065e104ecf742cb81f304263891;

// End of code for form form_0ebe0cfd226e9065e104ecf742cb81f304263891


/************************************************************/

static void *_cffi_types[] = {
/*  0 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *)
/*  1 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // _cffi_double_complex_t *
/*  2 */ _CFFI_OP(_CFFI_OP_POINTER, 38), // _cffi_double_complex_t const *
/*  3 */ _CFFI_OP(_CFFI_OP_NOOP, 2),
/*  4 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // double const *
/*  5 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // int const *
/*  6 */ _CFFI_OP(_CFFI_OP_POINTER, 55), // uint8_t const *
/*  7 */ _CFFI_OP(_CFFI_OP_POINTER, 60), // void *
/*  8 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/*  9 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *)
/* 10 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // _cffi_float_complex_t *
/* 11 */ _CFFI_OP(_CFFI_OP_POINTER, 39), // _cffi_float_complex_t const *
/* 12 */ _CFFI_OP(_CFFI_OP_NOOP, 11),
/* 13 */ _CFFI_OP(_CFFI_OP_POINTER, 44), // float const *
/* 14 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 15 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 16 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 17 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 18 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *)
/* 19 */ _CFFI_OP(_CFFI_OP_POINTER, 43), // double *
/* 20 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 21 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 22 */ _CFFI_OP(_CFFI_OP_NOOP, 4),
/* 23 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 24 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 25 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 26 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 27 */ _CFFI_OP(_CFFI_OP_FUNCTION, 60), // void()(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *)
/* 28 */ _CFFI_OP(_CFFI_OP_POINTER, 44), // float *
/* 29 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 30 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 31 */ _CFFI_OP(_CFFI_OP_NOOP, 13),
/* 32 */ _CFFI_OP(_CFFI_OP_NOOP, 5),
/* 33 */ _CFFI_OP(_CFFI_OP_NOOP, 6),
/* 34 */ _CFFI_OP(_CFFI_OP_NOOP, 7),
/* 35 */ _CFFI_OP(_CFFI_OP_FUNCTION_END, 0),
/* 36 */ _CFFI_OP(_CFFI_OP_POINTER, 37), // _Bool const *
/* 37 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 1), // _Bool
/* 38 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 49), // _cffi_double_complex_t
/* 39 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 48), // _cffi_float_complex_t
/* 40 */ _CFFI_OP(_CFFI_OP_POINTER, 41), // char const * *
/* 41 */ _CFFI_OP(_CFFI_OP_POINTER, 42), // char const *
/* 42 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 2), // char
/* 43 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 14), // double
/* 44 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 13), // float
/* 45 */ _CFFI_OP(_CFFI_OP_POINTER, 47), // int *
/* 46 */ _CFFI_OP(_CFFI_OP_POINTER, 5), // int const * *
/* 47 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 7), // int
/* 48 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 0), // ufcx_form
/* 49 */ _CFFI_OP(_CFFI_OP_POINTER, 50), // ufcx_integral * *
/* 50 */ _CFFI_OP(_CFFI_OP_POINTER, 51), // ufcx_integral *
/* 51 */ _CFFI_OP(_CFFI_OP_STRUCT_UNION, 1), // ufcx_integral
/* 52 */ _CFFI_OP(_CFFI_OP_ENUM, 0), // ufcx_integral_type
/* 53 */ _CFFI_OP(_CFFI_OP_POINTER, 54), // uint64_t *
/* 54 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 24), // uint64_t
/* 55 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 18), // uint8_t
/* 56 */ _CFFI_OP(_CFFI_OP_POINTER, 0), // void(*)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *)
/* 57 */ _CFFI_OP(_CFFI_OP_POINTER, 9), // void(*)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *)
/* 58 */ _CFFI_OP(_CFFI_OP_POINTER, 18), // void(*)(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *)
/* 59 */ _CFFI_OP(_CFFI_OP_POINTER, 27), // void(*)(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *)
/* 60 */ _CFFI_OP(_CFFI_OP_PRIMITIVE, 0), // void
};

static int _cffi_const_cell(unsigned long long *o)
{
  int n = (cell) <= 0;
  *o = (unsigned long long)((cell) | 0);  /* check that cell is an integer */
  return n;
}

static int _cffi_const_exterior_facet(unsigned long long *o)
{
  int n = (exterior_facet) <= 0;
  *o = (unsigned long long)((exterior_facet) | 0);  /* check that exterior_facet is an integer */
  return n;
}

static int _cffi_const_interior_facet(unsigned long long *o)
{
  int n = (interior_facet) <= 0;
  *o = (unsigned long long)((interior_facet) | 0);  /* check that interior_facet is an integer */
  return n;
}

static int _cffi_const_vertex(unsigned long long *o)
{
  int n = (vertex) <= 0;
  *o = (unsigned long long)((vertex) | 0);  /* check that vertex is an integer */
  return n;
}

static int _cffi_const_ridge(unsigned long long *o)
{
  int n = (ridge) <= 0;
  *o = (unsigned long long)((ridge) | 0);  /* check that ridge is an integer */
  return n;
}

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_form(ufcx_form *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { char const * *tmp = &p->signature; (void)tmp; }
  (void)((p->rank) | 0);  /* check that 'ufcx_form.rank' is an integer */
  (void)((p->num_coefficients) | 0);  /* check that 'ufcx_form.num_coefficients' is an integer */
  { int * *tmp = &p->original_coefficient_positions; (void)tmp; }
  { char const * * *tmp = &p->coefficient_name_map; (void)tmp; }
  (void)((p->num_constants) | 0);  /* check that 'ufcx_form.num_constants' is an integer */
  { int const * *tmp = &p->constant_ranks; (void)tmp; }
  { int const * * *tmp = &p->constant_shapes; (void)tmp; }
  { char const * * *tmp = &p->constant_name_map; (void)tmp; }
  { uint64_t * *tmp = &p->finite_element_hashes; (void)tmp; }
  { ufcx_integral * * *tmp = &p->form_integrals; (void)tmp; }
  { int * *tmp = &p->form_integral_ids; (void)tmp; }
  { int * *tmp = &p->form_integral_offsets; (void)tmp; }
}
struct _cffi_align__ufcx_form { char x; ufcx_form y; };

_CFFI_UNUSED_FN
static void _cffi_checkfld__ufcx_integral(ufcx_integral *p)
{
  /* only to generate compile-time warnings or errors */
  (void)p;
  { _Bool const * *tmp = &p->enabled_coefficients; (void)tmp; }
  { void(* *tmp)(float *, float const *, float const *, float const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_float32; (void)tmp; }
  { void(* *tmp)(double *, double const *, double const *, double const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_float64; (void)tmp; }
  { void(* *tmp)(_cffi_float_complex_t *, _cffi_float_complex_t const *, _cffi_float_complex_t const *, float const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_complex64; (void)tmp; }
  { void(* *tmp)(_cffi_double_complex_t *, _cffi_double_complex_t const *, _cffi_double_complex_t const *, double const *, int const *, uint8_t const *, void *) = &p->tabulate_tensor_complex128; (void)tmp; }
  (void)((p->needs_facet_permutations) | 0);  /* check that 'ufcx_integral.needs_facet_permutations' is an integer */
  (void)((p->coordinate_element_hash) | 0);  /* check that 'ufcx_integral.coordinate_element_hash' is an integer */
  (void)((p->domain) | 0);  /* check that 'ufcx_integral.domain' is an integer */
}
struct _cffi_align__ufcx_integral { char x; ufcx_integral y; };

static ufcx_form *_cffi_var_form_0ebe0cfd226e9065e104ecf742cb81f304263891(void)
{
  return &(form_0ebe0cfd226e9065e104ecf742cb81f304263891);
}

static const struct _cffi_global_s _cffi_globals[] = {
  { "cell", (void *)_cffi_const_cell, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "exterior_facet", (void *)_cffi_const_exterior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "form_0ebe0cfd226e9065e104ecf742cb81f304263891", (void *)_cffi_var_form_0ebe0cfd226e9065e104ecf742cb81f304263891, _CFFI_OP(_CFFI_OP_GLOBAL_VAR_F, 48), (void *)0 },
  { "interior_facet", (void *)_cffi_const_interior_facet, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "ridge", (void *)_cffi_const_ridge, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
  { "vertex", (void *)_cffi_const_vertex, _CFFI_OP(_CFFI_OP_ENUM, -1), (void *)0 },
};

static const struct _cffi_field_s _cffi_fields[] = {
  { "signature", offsetof(ufcx_form, signature),
                 sizeof(((ufcx_form *)0)->signature),
                 _CFFI_OP(_CFFI_OP_NOOP, 41) },
  { "rank", offsetof(ufcx_form, rank),
            sizeof(((ufcx_form *)0)->rank),
            _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "num_coefficients", offsetof(ufcx_form, num_coefficients),
                        sizeof(((ufcx_form *)0)->num_coefficients),
                        _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "original_coefficient_positions", offsetof(ufcx_form, original_coefficient_positions),
                                      sizeof(((ufcx_form *)0)->original_coefficient_positions),
                                      _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "coefficient_name_map", offsetof(ufcx_form, coefficient_name_map),
                            sizeof(((ufcx_form *)0)->coefficient_name_map),
                            _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "num_constants", offsetof(ufcx_form, num_constants),
                     sizeof(((ufcx_form *)0)->num_constants),
                     _CFFI_OP(_CFFI_OP_NOOP, 47) },
  { "constant_ranks", offsetof(ufcx_form, constant_ranks),
                      sizeof(((ufcx_form *)0)->constant_ranks),
                      _CFFI_OP(_CFFI_OP_NOOP, 5) },
  { "constant_shapes", offsetof(ufcx_form, constant_shapes),
                       sizeof(((ufcx_form *)0)->constant_shapes),
                       _CFFI_OP(_CFFI_OP_NOOP, 46) },
  { "constant_name_map", offsetof(ufcx_form, constant_name_map),
                         sizeof(((ufcx_form *)0)->constant_name_map),
                         _CFFI_OP(_CFFI_OP_NOOP, 40) },
  { "finite_element_hashes", offsetof(ufcx_form, finite_element_hashes),
                             sizeof(((ufcx_form *)0)->finite_element_hashes),
                             _CFFI_OP(_CFFI_OP_NOOP, 53) },
  { "form_integrals", offsetof(ufcx_form, form_integrals),
                      sizeof(((ufcx_form *)0)->form_integrals),
                      _CFFI_OP(_CFFI_OP_NOOP, 49) },
  { "form_integral_ids", offsetof(ufcx_form, form_integral_ids),
                         sizeof(((ufcx_form *)0)->form_integral_ids),
                         _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "form_integral_offsets", offsetof(ufcx_form, form_integral_offsets),
                             sizeof(((ufcx_form *)0)->form_integral_offsets),
                             _CFFI_OP(_CFFI_OP_NOOP, 45) },
  { "enabled_coefficients", offsetof(ufcx_integral, enabled_coefficients),
                            sizeof(((ufcx_integral *)0)->enabled_coefficients),
                            _CFFI_OP(_CFFI_OP_NOOP, 36) },
  { "tabulate_tensor_float32", offsetof(ufcx_integral, tabulate_tensor_float32),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float32),
                               _CFFI_OP(_CFFI_OP_NOOP, 59) },
  { "tabulate_tensor_float64", offsetof(ufcx_integral, tabulate_tensor_float64),
                               sizeof(((ufcx_integral *)0)->tabulate_tensor_float64),
                               _CFFI_OP(_CFFI_OP_NOOP, 58) },
  { "tabulate_tensor_complex64", offsetof(ufcx_integral, tabulate_tensor_complex64),
                                 sizeof(((ufcx_integral *)0)->tabulate_tensor_complex64),
                                 _CFFI_OP(_CFFI_OP_NOOP, 57) },
  { "tabulate_tensor_complex128", offsetof(ufcx_integral, tabulate_tensor_complex128),
                                  sizeof(((ufcx_integral *)0)->tabulate_tensor_complex128),
                                  _CFFI_OP(_CFFI_OP_NOOP, 56) },
  { "needs_facet_permutations", offsetof(ufcx_integral, needs_facet_permutations),
                                sizeof(((ufcx_integral *)0)->needs_facet_permutations),
                                _CFFI_OP(_CFFI_OP_NOOP, 37) },
  { "coordinate_element_hash", offsetof(ufcx_integral, coordinate_element_hash),
                               sizeof(((ufcx_integral *)0)->coordinate_element_hash),
                               _CFFI_OP(_CFFI_OP_NOOP, 54) },
  { "domain", offsetof(ufcx_integral, domain),
              sizeof(((ufcx_integral *)0)->domain),
              _CFFI_OP(_CFFI_OP_NOOP, 55) },
};

static const struct _cffi_struct_union_s _cffi_struct_unions[] = {
  { "ufcx_form", 48, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_form), offsetof(struct _cffi_align__ufcx_form, y), 0, 13 },
  { "ufcx_integral", 51, _CFFI_F_CHECK_FIELDS,
    sizeof(ufcx_integral), offsetof(struct _cffi_align__ufcx_integral, y), 13, 8 },
};

static const struct _cffi_enum_s _cffi_enums[] = {
  { "$ufcx_integral_type", 52, _cffi_prim_int(sizeof(ufcx_integral_type), ((ufcx_integral_type)-1) <= 0),
    "cell,exterior_facet,interior_facet,vertex,ridge" },
};

static const struct _cffi_typename_s _cffi_typenames[] = {
  { "ufcx_form", 48 },
  { "ufcx_integral", 51 },
  { "ufcx_integral_type", 52 },
  { "ufcx_tabulate_tensor_complex128", 0 },
  { "ufcx_tabulate_tensor_complex64", 9 },
  { "ufcx_tabulate_tensor_float32", 27 },
  { "ufcx_tabulate_tensor_float64", 18 },
};

static const struct _cffi_type_context_s _cffi_type_context = {
  _cffi_types,
  _cffi_globals,
  _cffi_fields,
  _cffi_struct_unions,
  _cffi_enums,
  _cffi_typenames,
  6,  /* num_globals */
  2,  /* num_struct_unions */
  1,  /* num_enums */
  7,  /* num_typenames */
  NULL,  /* no includes */
  61,  /* num_types */
  0,  /* flags */
};

#ifdef __GNUC__
#  pragma GCC visibility push(default)  /* for -fvisibility= */
#endif

#ifdef PYPY_VERSION
PyMODINIT_FUNC
_cffi_pypyinit_libffcx_forms_f9460830725f7d7c5dac003b7f248d97359f8a1f(const void *p[])
{
    p[0] = (const void *)0x2601;
    p[1] = &_cffi_type_context;
#if PY_MAJOR_VERSION >= 3
    return NULL;
#endif
}
#  ifdef _MSC_VER
     PyMODINIT_FUNC
#  if PY_MAJOR_VERSION >= 3
     PyInit_libffcx_forms_f9460830725f7d7c5dac003b7f248d97359f8a1f(void) { return NULL; }
#  else
     initlibffcx_forms_f9460830725f7d7c5dac003b7f248d97359f8a1f(void) { }
#  endif
#  endif
#elif PY_MAJOR_VERSION >= 3
PyMODINIT_FUNC
PyInit_libffcx_forms_f9460830725f7d7c5dac003b7f248d97359f8a1f(void)
{
  return _cffi_init("libffcx_forms_f9460830725f7d7c5dac003b7f248d97359f8a1f", 0x2601, &_cffi_type_context);
}
#else
PyMODINIT_FUNC
initlibffcx_forms_f9460830725f7d7c5dac003b7f248d97359f8a1f(void)
{
  _cffi_init("libffcx_forms_f9460830725f7d7c5dac003b7f248d97359f8a1f", 0x2601, &_cffi_type_context);
}
#endif

#ifdef __GNUC__
#  pragma GCC visibility pop
#endif
